SEARCH_TAGS = ["sports", "sports goods", "fitness", "fitness", "sports equipment", "sports equipment",
               "sports gear", "sports store", "TRX", "resistance bands", "fitness mat", "sleeping pad"]

CATEGORY_MAP = {
    'rolyky-ta-zahyst': 120326074,
    'yedinoborstva': 119043080,
    'samokaty-ta-skejty': 119749934,
    'velobig-ta-velosyped': 119750501,
    'gojdalka': 119749906,
    'nastilni-igry': 119749880,
    'komandnye-vidy-sporta': 119043274,
    'sport': 119041274,
    'batut': 119749909,
    'fitnes': 119008303,
    'trenirovki': 119749823,
    'turizm-ta-vidpochinok': 119749876,
}


CHANGES_PRICE = {
    'GC-0735': '200',
    'GC-0735-1': '200',
    'GC-0835': '220',
    'GC-0835-1': '220',
    'GRX-071BK': '220',

}

prom_category_mappings = {
    '287': 'https://prom.ua/ua/Sportivnye-flyagi',
    '289': 'https://prom.ua/ua/Bodibary',
    '291': 'https://prom.ua/ua/Ganteli-grify-trenazhery-dlya-tyazheloj-atletiki',
    '292': 'https://prom.ua/ua/Kovriki-dlya-jogi-i-fitnesa',
    '293': 'https://prom.ua/ua/Drugie-trenazhery',
    '296': 'https://prom.ua/ua/Bloki-dlya-jogi',
    '298': 'https://prom.ua/ua/Fitboly',
    '299': 'https://prom.ua/ua/Medboly',
    '308': 'https://prom.ua/ua/Obruchi-gimnasticheskie',
    '312': 'https://prom.ua/ua/Perchatki-dlya-fitnesa',
    '313': 'https://prom.ua/ua/Skakalki',
    '316': 'https://prom.ua/ua/Step-doski',
    '318': 'https://prom.ua/ua/Sportivnye-utyazheliteli',
    '319': 'https://prom.ua/ua/Espandery',
    '324': 'https://prom.ua/ua/Lyamki-atleticheskie',
    '325': 'https://prom.ua/ua/Ganteli-grify-trenazhery-dlya-tyazheloj-atletiki',
    '326': 'https://prom.ua/ua/Perchatki-dlya-fitnesa',
    '304': 'https://prom.ua/ua/Step-doski',
    '335': 'https://prom.ua/ua/Sportivnye-stenki',
    '339': 'https://prom.ua/ua/Tovary-dlya-trenerov-i-sudej',
    '357': 'https://prom.ua/ua/Lyamki-poyasa-atleticheskie',
    '355': 'https://prom.ua/ua/Perchatki-dlya-fitnesa',
    '351': 'https://prom.ua/ua/Ganteli-grify-trenazhery-dlya-tyazheloj-atletiki',
    '348': 'https://prom.ua/ua/Ganteli-grify-trenazhery-dlya-tyazheloj-atletiki',
    '347': 'https://prom.ua/ua/Lyamki-atleticheskie',
    '366': 'https://prom.ua/ua/Bodibary',
    '371': 'https://prom.ua/ua/Komplektuyuschie-i-aksessuary-dlya-trenazherov',
    '374': 'https://prom.ua/ua/Fiksatory-kolennogo-sustava',
    '372': 'https://prom.ua/ua/Fiksatory-kolennogo-sustava',
    '379': 'https://prom.ua/ua/Fiksatory-kolennogo-sustava',
    '380': 'https://prom.ua/ua/Zaschitnye-nalokotniki-1',
    '391': 'https://prom.ua/ua/Fiksatory-luchezapyastnogo-sustava-i-paltsev-kisti',
    '395': 'https://prom.ua/ua/Sportivnye-myachi',
    '396': 'https://prom.ua/ua/Sportivnye-myachi',
    '393': 'https://prom.ua/ua/Sportivnye-myachi',
    '408': 'https://prom.ua/ua/Sportivnye-myachi',
    '410': 'https://prom.ua/ua/Sportivnye-myachi',
    '427': 'https://prom.ua/ua/Sportivnye-myachi',
    '456': 'https://prom.ua/ua/Sportivnye-myachi',
    '460': 'https://prom.ua/ua/Sportivnye-myachi',
    '462': 'https://prom.ua/ua/Sportivnye-myachi',
    '463': 'https://prom.ua/ua/Sportivnye-myachi',
    '403': 'https://prom.ua/ua/Sportivnye-myachi',
    '400': 'https://prom.ua/ua/Basketbol-obschee',
    '401': 'https://prom.ua/ua/Lyamki-atleticheskie',
    '402': 'https://prom.ua/ua/Basketbolnye-stojki-schity-koltsa',
    '405': 'https://prom.ua/ua/Lyamki-atleticheskie',
    '411': 'https://prom.ua/ua/Nakolenniki-dlya-skejtbordistov-nakolenniki-dlya-rollerov-nakolenniki-dlya-sporta',
    '413': 'https://prom.ua/ua/Setki-dlya-igrovyh-ploschadok',
}

TITLES_CSV = [
    'Product_Code', 'Item_Name', 'Item_Name_Ukr', 'Search_Queries', 'Search_Queries_Ukr',
    'Description', 'Description_Ukr', 'Product_Type', 'Price', 'Price_From', 'Currency', 'Unit_of_Measurement',
    'Image_Link', 'Weight_kg', 'Width_cm', 'Height_cm', 'Length_cm', 'Availability',
    'Discount', 'Discount_Period_From', 'Discount_Period_To', 'Label', 'Manufacturer',
    'Country_of_Origin', 'HTML_Title', 'HTML_Title_Ukr', 'HTML_Description', 'HTML_Description_Ukr',
    'HTML_Keywords', 'HTML_Keywords_Ukr', 'Gifts', 'Related_Products', 'Gift_IDs',
    'Related_Product_IDs', 'Group_Number', 'Group_Name', 'Subdivision_Link', 'Packaging_Method',
    'Personal_Notes', 'Product_on_Website', 'Marking_Code_(GTIN)', 'Device_Number_(MPN)',
    'Product_Identifier', 'Unique_Identifier', 'Subdivision_Identifier', 'Group_Identifier',
    'Variant_Group_ID', 'Product_Location', 'Characteristic_Name', 'Characteristic_Unit_of_Measurement',
    'Characteristic_Value'
]
